### ISSUE TITLE
我觉得代码块显示有待优化

### ISSUE THREAD

**Issue by bd-dxg** [mingluosunyi/typora-theme-ava-diana#1]
![QQ20210921-152427](https://user-images.githubusercontent.com/34816426/134128898-487104e1-03d2-4c76-ba0a-ad5794208076.jpg)

如图所示

**Comment by mingluosunyi** [comment]
已经修改了，现在代码应该变得更加清晰了一些。

**Comment by mingluosunyi** [comment]
行内代码用的是等宽字体，应该还是有一点区别的，如果有更好的方案也可以告诉我哈。
