### ISSUE TITLE
每级标题缩进是特意设计的吗？

### ISSUE THREAD

**Issue by zzzzkzz** [mingluosunyi/typora-theme-ava-diana#5]
如图，标题每级缩进，正文不会缩进看起来很怪，不知道是bug还是feature捏
<img width="534" alt="Screen Shot 2021-11-14 at 9 18 20 AM" src="https://user-images.githubusercontent.com/71886517/141663896-a9e21a23-43f2-48d0-82cd-14f8256a04d7.png">

**Comment by mingluosunyi** [comment]
算是有特意设计的，主要是因为我觉得段落的缩进可以通过人为添加空格符来调节，而标题的缩进如果用空格调节，在[TOC]和左侧的导航模块中，标题左边也会相应地添加上空格字符,不太美观，所以就在样式中给不同级别的标题加了左边距。如果想要去掉可以搜索css样式表中的h2-h5 ，把里面的margin-left属性删掉。

**Comment by zzzzkzz** [comment]
好滴!主题做的很漂亮🤤嘿嘿..🤤
